export enum ContainerIoC {
  Application = 'Application',
  LoggerInterface = 'LoggerInterface',
  ConfigInterface = 'ConfigInterface',
  DatabaseInterface = 'DatabaseInterface',
  UserService = 'UserService',
  UserModel = 'UserModel',
  UserController = 'UserController',
  FilmService = 'FilmService',
  FilmModel = 'FilmModel',
  FilmController = 'FilmController',
  FilmFavoriteController = 'FilmFavoriteController',
  FilmPromoController = 'FilmPromoController',
  CommentModel = 'CommentModel',
  CommentService = 'CommentService',
  CommentController = 'CommentController',
  ExceptionFilter = 'ExceptionFilter',
}
