export type MockData = {
  titles: string[]
  descriptions: string[]
  genres: string[]
  videoLinks: string[]
  starrings: string[]
  directors: string[]
  posterImages: string[]
  bgImages: string[]
  bgColors: string[]
  userNames: string[]
  emails: string[]
  avatars: string[]
  passwords: string[]
}
