### Variables
@port = 3333

###

# Mock data
GET http://localhost:{{port}}/api HTTP/1.1

###

# Users

## Check user's token
GET http://localhost:4000/users/login HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJlbWFpbCI6InRvcmFuc0BvdmVybG9vay5uZXQiLCJpZCI6IjYyOTM0MDgyZDFlMDU5MDBlMmVmYWVjMyIsImlhdCI6MTY1MzkwMzA1OSwiZXhwIjoxNjU0MDc1ODU5fQ.yMN3DID7PoMO1I4-fgwjGVWjdfnpQsCA8TL02APb-rU

###

## User registration

POST http://localhost:{{port}}/users/register HTTP/1.1
Content-Type: application/json

{
  "userName": "Jack",
  "email": "torans@overlook.net",
  "avatarPath": "torrance.png",
  "password": "shining"
}

###

## User authorization

POST http://localhost:{{port}}}/users/login HTTP/1.1
Content-Type: application/json

{
  "email": "torans@overlook.net",
  "password": "123456"
}

###

# Films
## Get film details

GET http://localhost:{{port}}/films/62711a50b0e24a624d49ffdc HTTP/1.1

###

## Get films list

GET http://localhost:{{port}}/films HTTP/1.1

###

## Create film

GET http://localhost:{{port}}/films HTTP/1.1

{
  "name": "Fast And Furious",
  "description": "Dominic Toretto is a gang leader who is accused of hijacking trucks and stealing over a million dollars...",
  "postDate": "2022-04-06T08:45:40.283Z",
  "genre": "crime",
  "releaseYear": "2001",
  "rating": 7.7,
  "previewVideoLink": "http://previewvideo1.com",
  "videoLink": "http://video1.com",
  "starring": [
    "Vin Diesel",
    "Paul Walker",
    "Michelle Rodriguez"
  ],
  "director": "Justin Lin",
  "runTime": 106,
  "commentsCount": 40,
  "userId": "633041890aa1e923453c2947",
  "posterImage": "http://poster2/1.jpg",
  "bgImage": "http://bg2/1.jpg",
  "bgColor": "#ffffff"
}

###

## Delete film

DELETE http://localhost:{{port}}/films/62711a50b0e24a624d49ffdc HTTP/1.1

###

## Update film

PATCH http://localhost:{{port}}/films/62711a50b0e24a624d49ffdc HTTP/1.1
Content-Type: application/json

{
  "name": "Fast And Furious",
  "description": "Dominic Toretto is a gang leader who is accused of hijacking trucks and stealing over a million dollars...",
  "postDate": "2022-04-06T08:45:40.283Z",
  "genre": "crime",
  "releaseYear": "2001",
  "rating": 7.7,
  "previewVideoLink": "http://previewvideo1.com",
  "videoLink": "http://video1.com",
  "starring": [
    "Vin Diesel",
    "Paul Walker",
    "Michelle Rodriguez"
  ],
  "director": "Justin Lin",
  "runTime": 106,
  "commentsCount": 40,
  "userId": "633041890aa1e923453c2947",
  "posterImage": "http://poster2/1.jpg",
  "bgImage": "http://bg2/1.jpg",
  "bgColor": "#ffffff"
}

###

## List of films of certain genre

GET http://localhost:{{port}}/films/62823cb2c5a64ce9f1b50eba?limit=60 HTTP/1.1

###

## Create comment
POST http://localhost:{{port}}/comments HTTP/1.1
Content-Type: application/json

{
  "text": "Great movie!",
  "rating": 7.7,
  "postDate": "2022-04-06T08:45:40.283Z",
  "userId": "628a27d729c45f2bf9f67ff2",
  "filmId": "628a27d729c45f2bf9f6806a"
}

###

## List of comments for the film
GET http://localhost:{{port}}/films/628a27d729c45f2bf9f6806a/comments HTTP/1.1

###


## Upload avatar

POST http://localhost:{{port}}/users/62823cb2c5a64ce9f1b50eb6/avatar HTTP/1.1
Content-Type: multipart/form-data; boundary=----WebKitFormBoundary7MA4YWxkTrZu0gW

------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="avatar"; filename="picture.png"
Content-Type: image/png

< /Users/tmp/picture.png
------WebKitFormBoundary7MA4YWxkTrZu0gW--
